Repository truckersmp-cli/truckersmp-cli, pull requests merged in 2024-05, with the labels that each got.

#351 Avoid using the "**" pattern
  truckersmp_cli/utils.py
Labels: pr:bugfix

#352 Release 0.10.2
  RELEASE
  truckersmp_cli/utils.py
Labels: pr:release

#354 GitHub Actions: Install setuptools before uploading package to PyPI
  .github/workflows/auto_release.yaml
Labels: pr:infrastructure

#356 Release 0.10.2.1
  .github/workflows/auto_release.yaml
  RELEASE
Labels: pr:release

#355 proton.json: Support Proton 9.0 (2805730)
  truckersmp_cli/proton.json
Labels: pr:external

#358 steamruntime.json: Use Steam Runtime 3.0 'sniper' for Proton 8.0 or newer
  truckersmp_cli/steamcmd.py
  truckersmp_cli/steamruntime.json
Labels: pr:external
